name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to the repository
    steps:
      - uses: actions/checkout@v4
      - name: Create output directory
        run: mkdir -p output
      - uses: Platane/snk@master
        id: snk
        with:
          github_user_name: Cr4tes
          svg_output_path: output/github-contribution-grid-snake.svg
      - name: Debug output directory
        run: ls -la output
      - name: Verify SVG exists
        run: test -f output/github-contribution-grid-snake.svg || exit 1
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}